### ISSUE TITLE
Add `fetchMore` to query result record and properly type it

### ISSUE THREAD

**Issue by jfrolich** [reasonml-community/reason-apollo-client#47]
It's parametrically typed here (basically accepts any parameters). OR add it to the query extension?

https://github.com/reasonml-community/reason-apollo-client/blob/38d5b88be502061afabb50866437a2834c3a15c8/src/%40apollo/client/react/types/ApolloClient__React_Types.re#L373

Also we could accept normal variables instead of `jsVariables`, so we don't have to manually convert it.

**Comment by jfrolich** [comment]
Maybe I am wrong and it infers the data correctly?

**Comment by jeddeloh** [comment]
#### Adding `fetchMore` to the query result record

Isn't it on there already? It has an abstract type `useMethodFunctionsInThisModuleInstead`. Are you proposing that we drop the separate function and allow the method to be called on the record directly? If that's what you're proposing (I don't know if it is), in many ways I would prefer that, and I don't think in this case it would cause any problems. However, there are definitely methods in the library that use the _this_ context and will fail, and for that reason, I've tried to be consistent and the rule is that methods are always called with a `bs.send` binding. We could provide both for things we know are safe? There are also methods like `subscibeToMore` where I was (personally) unable to express its polymorphic nature on a record type.

#### Also we could accept normal variables instead of jsVariables

Yes, great catch. I think I just missed this entirely when converting the rest.

#### Perhaps it's possible to attach the whole definition as a first class module? (then we also have serializeVariables).

Sounds good.

**Comment by jfrolich** [comment]
By the way these are some observations whilst we convert our codebase 😁

**Comment by jfrolich** [comment]
It's looking really great!

**Comment by jfrolich** [comment]
Btw `fetchMore` and `refetch` were implemented as record fields in `reason-apollo-hooks`, and I am not aware of problems with `this`

**Comment by jeddeloh** [comment]
> By the way these are some observations whilst we convert our codebase 😁
It's looking really great!

Awesome! I think there are still probably a kink or two to work out, but we'll hopefully get things sorted shortly now that there's another person seriously using this 😄 

> Btw fetchMore and refetch were implemented as record fields in reason-apollo-hooks, and I am not aware of problems with this. (But actually I don't really mind the other API as long as it's safe)

Yeah, there's nothing wrong with using it as a record. This issue, for me, was one of consistency in how we document and use the API. Now that you mention it, I guess the best case scenario is that we say in the docs "always use the `bs.send` methods" and do so in the examples as well, but we also provide them on the record for the most part for advanced users.

**Comment by jfrolich** [comment]
> Yeah, there's nothing wrong with using it as a record. This issue, for me, was one of consistency in how we document and use the API (because it's not safe for all methods). Now that you mention it, I guess the best case scenario is that we say in the docs "always use the `bs.send` methods" and do so in the examples as well, but we also provide them on the record for the most part for advanced users.

Nah actually that would be confusing imo. Better to have a single place.

**Comment by jfrolich** [comment]
I am really impressed by the rigor of this library btw 😄 👍

**Comment by jeddeloh** [comment]
> Nah actually that would be confusing imo. Better to have a single place.

Yeah, I think you're right. Talking about this has given me another idea, though. 🤔 I'll experiment and circle back if it's successful.

**Comment by jeddeloh** [comment]
Yes, I was indeed thinking of this all wrong! See #48. I think it's very possible to put `fetchMore` directly on query result and only use `bs.send` methods internally.

**Comment by jeddeloh** [comment]
> I also saw that you attach the parse and serialize functions to the result. Perhaps it's possible to attach the whole definition as a first class module? (then we also have serializeVariables).

Note that this is no longer necessary if we go in the direction of #48.

**Comment by jeddeloh** [comment]
Closing now that v1.0.0-beta.0 is released
